#File in .gitignore

#region [red] CONFIGURATION

TKINTER_SCALING = 0.4
GRID_WIDTH = 50
GRID_HEIGHT = 50
GRID_UNIT = TKINTER_SCALING*40
THICKNESS = TKINTER_SCALING*4

FONT_FAMILY = "Helvetica"
FONT_SIZE = 20
FONT_SIZE_MENU=35

FILE_DIRECTORY = ""
FILE_NAME = "testcircuit2"
PROGRAM_NAME = "testprog"

BUTTON_WIDTH = 6
TOOL_PANEL_WIDTH = TKINTER_SCALING*100

CHRONOGRAM_WIDTH = TKINTER_SCALING*800
CHRONOGRAM_MARGIN_VERTICAL = TKINTER_SCALING*40
CHRONOGRAM_MARGIN_HORIZONTAL = 40

SHIFT_MOVE_PERCENTAGE = 0.5

DT_PER_CC = 5

#endregion